import { Users, Clock, Layout, Save, Zap, Gem, Snowflake } from 'lucide-react'
export const adjectives = [
  'Happy',
  'Clever',
  'Brave',
  'Gentle',
  'Swift',
  'Bright',
  'Kind',
  'Wise',
  'Calm',
  'Bold',
  'Merry',
  'Noble',
  'Proud',
  'Quick',
  'Smart',
  'Witty',
  'Cyber',
  'Digital',
  'Quantum',
  'Neural',
  'Binary',
  'Mecha',
  'Techno',
  'Crypto',
  'Nano',
  'Proto',
  'Futuristic',
  'Mechanical',
  'Synthetic',
  'Autonomous',
  'Virtual',
  'Robotic',
  'AI',
  'Digitalized',
  'Shiny',
  'Vivid',
  'Silent',
  'Fierce',
  'Stealthy',
  'Luminous',
  'Cold',
  'Radiant',
  'Mysterious',
  'Graceful',
  'Stellar',
  'Agile',
  'Reflective',
  'Energetic',
  'Glowing',
  'Electric',
  'Cosmic',
  'Monstrous',
  'Infinite',
  'Imposing',
  'Dreamy',
  'Hyper',
  'Supreme',
  'Rogue',
  'Anomalous',
  'Evolving',
  'Unbreakable',
  'Fluid',
  'Regenerative',
  'Eccentric',
  'Disruptive',
  'Cybernetic',
  'Unseen',
  'Infinite',
  'Glimmering',
  'Divinely',
  'Time-Warped',
  'Shimmering',
  'Speedy',
  'Ultimate',
  'Calculated',
  'Powerful',
  'Legendary',
  'Divine',
  'Vengeful',
  'Mystic',
  'Beastly',
  'Fateful',
  'Ancient',
  'Ethereal',
  'Cursed',
  'Invincible',
  'Awakened',
  'Majestic',
  'Endless',
  'Immortal',
  'Cyber-Warrior',
]
export const nouns = [
  'Panda',
  'Tiger',
  'Eagle',
  'Dolphin',
  'Fox',
  'Wolf',
  'Bear',
  'Lion',
  'Hawk',
  'Owl',
  'Dragon',
  'Phoenix',
  'Falcon',
  'Lynx',
  'Leopard',
  'Jaguar',
  'Android',
  'Cyborg',
  'Matrix',
  'Vector',
  'Nexus',
  'Titan',
  'Byte',
  'Circuit',
  'Cortex',
  'Cipher',
  'Mech',
  'Bot',
  'Gizmo',
  'Drone',
  'Automaton',
  'Mechanoid',
  'Synth',
  'Robot',
  'Cybernetic',
  'NanoBot',
  'AI Unit',
  'Technoid',
  'Mech-Drone',
  'Warlock',
  'Oracle',
  'Sentinel',
  'Shifter',
  'Specter',
  'Vortex',
  'Ether',
  'Phantom',
  'Nomad',
  'Nexus-Unit',
  'Illusion',
  'Seraph',
  'Guardian',
  'Exoskeleton',
  'Glitch',
  'Valkyrie',
  'Saber',
  'Beast',
  'Kenshiro',
  'Naruto',
  'Luffy',
  'Goku',
  'Ichigo',
  'Edward',
  'Saitama',
  'Eren',
  'Deku',
  'Kamina',
  'Sakura',
  'Usagi',
  'Kaguya',
  'Makoto',
  'Shinji',
  'Lelouch',
  'Rintarou',
  'Yuji',
  'Natsu',
  'Yugi',
  'Ash',
  'Kenshiro',
  'Inuyasha',
  'Simon',
  'Kirito',
  'Gintoki',
  'Ainz',
  'Yuno',
  'Light',
  'L',
  'Vash',
  'Holo',
  'Reigen',
  'Mob',
  'Mikasa',
  'Roronoa',
  'Kamina',
  'Saber',
  'Kirei',
  'Vash',
  'Archer',
  'Yuno',
  'Akira',
  'Saitama',
  'Mob',
  'Tanjiro',
  'Nezuko',
  'Rengoku',
  'Inosuke',
  'Zenitsu',
]
export const navLinks = [
  { href: '/#features', label: 'Features' },
  { href: '/plans', label: 'Pricing' },
  { href: '/#contact', label: 'Contact' },
]

export const plans = [
  {
    name: 'Free',
    icon: Snowflake,
    description: 'Perfect for individuals and small teams getting started',
    price: '0',
    badge: null,
    features: [
      {
        icon: Users,
        title: '100 team members',
        description: 'Collaborate with up to 100 users',
      },
      {
        icon: Layout,
        title: '30 rooms',
        description: 'Create up to 30 active rooms',
      },
      {
        icon: Save,
        title: '10 saved rooms',
        description: 'Save up to 10 rooms for later',
      },
      {
        icon: Clock,
        title: '60 min time limit',
        description: 'Session duration up to 60 minutes',
      },
    ],
  },
  {
    name: 'Pro',
    icon: Gem,
    description: 'Perfect for growing teams and organizations',
    price: '10',
    badge: 'Most popular',
    features: [
      {
        icon: Users,
        title: '200 team members',
        description: 'Collaborate with up to 200 users',
      },
      {
        icon: Layout,
        title: '100 rooms',
        description: 'Create up to 100 active rooms',
      },
      {
        icon: Save,
        title: '50 saved rooms',
        description: 'Save up to 50 rooms for later',
      },
      {
        icon: Zap,
        title: '200 min time limit',
        description: 'Extended sessions up to 200 minutes',
      },
    ],
  },
]
